yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('group_list/',views.group_list,name='list' ),
    path('group/<slug:slug>/', views.group_posts, name = 'group_list')
    ]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from operator import mod
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()
Group = get_user_model()

class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField()
    def __str__(self):
        return self.title

class Post(models.Model):
    text = models.TextField(max_length=200)
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True, 
        null=True, 
        on_delete=models.CASCADE)



    

yatube/posts/views.py
from tempfile import template
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Post, Group

def index(request):
    # Одна строка вместо тысячи слов на SQL:
    # в переменную posts будет сохранена выборка из 10 объектов модели Post,
    # отсортированных по полю pub_date по убыванию (от больших значений к меньшим)
    posts = Post.objects.order_by('-pub_date')[:10]
    title = "Последние обновления на сайте"
    # В словаре context отправляем информацию в шаблон
    context = {
        'posts': posts,
        'title': title
    }
    return render(request, 'posts/index.html', context)

def group_list(request):
    template = 'posts\group_list.html'
    content = {'text':'123'}
    return render(request, template, content)
    
def group_posts(request, slug):
    # Функция get_object_or_404 получает по заданным критериям объект 
    # из базы данных или возвращает сообщение об ошибке, если объект не найден.
    # В нашем случае в переменную group будут переданы объекты модели Group,
    # поле slug у которых соответствует значению slug в запросе
    group = get_object_or_404(Group, slug=slug)
    title = f"Записи сообщества {group}"
    # Метод .filter позволяет ограничить поиск по критериям.
    # Это аналог добавления
    # условия WHERE group_id = {group_id}
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    content = {
        'title': title,
        'group': group,
        'posts': posts,

    }
    return render(request, 'posts/group_list.html', content) 

yatube/templates/base.html
{% load static %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css\bootstrap.min.css' %}">
    <title>{{title}}</title>
  </head>
  <body>
    <header>
     {{ text }}
     {% include 'includes\header.html' %}     
    </header>
    <main> 
        {% block content %}
            Content?
        {% endblock content %}
    </main>       
    <footer class="border-top text-center py-3">
        {% include 'includes\footer.html' %}
    </footer>
  </body>

yatube/templates/includes/footer.html
<!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
<p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>  

yatube/templates/includes/header.html
{% load static %}
    <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
    <!-- В дальнейшем тут будет создано полноценное меню -->
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
          <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
          <span style="color:red">Ya</span>tube</a>
        </a>
      </div>
    </nav>      

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block content %}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">     
        <h1>{{title}}</h1>
        {% for post in posts %}
        <article>
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Группа: {{post.group}}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>      
          <p>
            {{post.text}}
          </p>
        </article>
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}  
        <!-- под последним постом нет линии -->
      </div>

{% endblock content %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">     
        <h1>{{title}}</h1>
        {% for post in posts %}
        <article>
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Группа: {{post.group}}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>      
          <p>
            {{post.text}}
          </p>
          {% if post.group %}   
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% endif %}
        </article>
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}  
        <!-- под последним постом нет линии -->
      </div>

{% endblock content %}